title: "Мой блог"
description: "Описание моего блога"
baseurl: ""
url: "https://example.com"

markdown: kramdown
permalink: pretty

author:
  name: "Ваше Имя"
  telegram: "ITfinds"

navigation:
  - name: Главная
    link: /
  - name: Обо мне
    link: /about
  - name: Блог
    link: /blog
  - name: Контакты
    link: /contact

paginate: 5
paginate_path: "/blog/page:num/"

telegram_channel: "https://t.me/ITfinds"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
