title:              Blog Bit
email:              
description:        Всё о блокчейн, криптовалютах и трейдинге.
author:             Root
baseurl:            ""
url:                "https://blogbit.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
telegram_username: criptoblogbit 
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
future: true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag