# Site settings
title: "Clean Blog"
email: "your-email@example.com"
description: "A Clean Blog Theme for Jekyll"
baseurl: "" # подпуть, если сайт в поддиректории
url: "https://yourdomain.com" # основной домен

# Author settings
author: "Start Bootstrap"
twitter_username: SBootstrap
github_username: StartBootstrap
facebook_username: StartBootstrap

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
theme_color: "#0085A1"
backgrounds:
  index: "/assets/img/home-bg.jpg"
  about: "/assets/img/about-bg.jpg"
  contact: "/assets/img/contact-bg.jpg"
  post: "/assets/img/post-bg.jpg"

# Локальные ресурсы (заменяем CDN)
local_resources: true
local_bootstrap: true
local_fontawesome: true
local_fonts: true

sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"
