title: "Мой блог"
description: "Описание моего блога"
baseurl: ""
url: "https://example.com"

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
timezone: Europe/Moscow

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

author:
  name: "Ваше Имя"
  telegram: "ITfinds"

navigation:
  - name: Главная
    link: /
  - name: Обо мне
    link: /about
  - name: Блог
    link: /blog
  - name: Контакты
    link: /contact

# Пагинация для Jekyll Paginate v2
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

telegram_channel: "https://t.me/ITfinds"

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
